language: python

sudo: false

cache: pip

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=default
  # no lettuce on Python 3
  allow_failures:
  - python: 3.6
    env: TEST_TARGET=default

before_install:
    - pip install -r requirements.txt -r requirements-dev.txt

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install pyGDP-${version}.tar.gz && popd


script:
  - cp -r Lettuce_Tests/ /tmp
  - cd /tmp && lettuce --tag=-not_working Lettuce_Tests
